# Generated by Django 5.2.12 on 2026-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('benefactor', 'Benefactor'), ('health_assistant', 'Health Assistant'), ('doctor', 'Doctor'), ('service_center', 'Service Center'), ('charity_center', 'Charity Center'), ('social_work_unit', 'Social Work Unit')], max_length=30),
        ),
    ]
