# Generated by Django 5.2.12 on 2026-05-13 14:00

import django.db.models.deletion
from django.db import migrations, models


def clear_doctor_rows_for_fk_schema(apps, schema_editor):
    Doctor = apps.get_model("api", "Doctor")
    Doctor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cooperation_patient_count',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cooperation_period',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cooperation_period_description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='cooperation_scope',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='county',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='free_duration_unit',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='free_duration_value',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='other_service',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='paramedical_service',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='participation_types',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rehabilitation_service',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='services',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='target_organization_type',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='target_subset_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='target_subset_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('benefactor', 'Benefactor'), ('health_assistant', 'Health Assistant'), ('doctor', 'Doctor'), ('service_center', 'Service Center'), ('charity_center', 'Charity Center'), ('social_work_unit', 'Social Work Unit')], max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='cooperation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cooperationtype'),
        ),
        migrations.RunPython(clear_doctor_rows_for_fk_schema, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialty'),
        ),
    ]
