# Generated by Django 5.2.12 on 2026-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_lookup_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='familiar2_name',
            new_name='contact2_full_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='familiar2_phone',
            new_name='contact2_phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='familiar1_family',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='familiar1_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='familiar1_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='familiar2_family',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact1_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
