# Generated by Django 5.2.12 on 2026-05-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_familiar2_name_patient_contact2_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='county',
        ),
    ]
