# Generated by Django 5.2.12 on 2026-05-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cooperationtype_name_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCooperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAssistantCooperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='SUBSET_TYPE',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='county',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='education',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='how_know',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='introducer_mobile',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='introducer_name',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='introducer_national_code',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='introducer_type',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='introduction_letter',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='job',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='subset_name',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='volunteer_skills',
        ),
        migrations.RemoveField(
            model_name='healthassistant',
            name='work_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='presenter_first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='presenter_last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='presenter_national_code',
        ),
        migrations.AddField(
            model_name='healthassistant',
            name='health_assistance_code',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='introducer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.healthassistant'),
        ),
        migrations.AlterField(
            model_name='healthassistant',
            name='cooperation_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='covered_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coveredorganization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cooperation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctorcooperationtype'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.education'),
        ),
        migrations.AlterField(
            model_name='healthassistant',
            name='cooperation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.healthassistantcooperationtype'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='housing_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.housingstatus'),
        ),
        migrations.CreateModel(
            name='IndividualHealthAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('job', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('work_address', models.TextField()),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.education')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender')),
                ('health_assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='api.healthassistant')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.insurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobstatus'),
        ),
        migrations.CreateModel(
            name='OrganizationHealthAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director_first_name', models.CharField(max_length=100)),
                ('director_last_name', models.CharField(max_length=100)),
                ('director_phone_number', models.CharField(max_length=11)),
                ('director_landline_number', models.CharField(max_length=11)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('social_unit_head_first_name', models.CharField(max_length=100)),
                ('social_unit_head_last_name', models.CharField(max_length=100)),
                ('social_unit_head_phone_number', models.CharField(max_length=100)),
                ('social_unit_head_landline_number', models.CharField(max_length=100)),
                ('health_assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to='api.healthassistant')),
                ('organization_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.organizationtype')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialWorkUnit',
        ),
        migrations.DeleteModel(
            name='CooperationType',
        ),
    ]
