# Generated by Django 5.2.12 on 2026-05-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_coveredorganization_doctorcooperationtype_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='benefactor',
            name='how_know',
        ),
        migrations.RemoveField(
            model_name='benefactor',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='benefactor',
            name='volunteer_skills',
        ),
        migrations.AddField(
            model_name='benefactor',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender'),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.DeleteModel(
            name='CharityCenter',
        ),
        migrations.DeleteModel(
            name='ServiceCenter',
        ),
    ]
