# Generated by Django 5.2.12 on 2026-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_servicecenter_user_remove_benefactor_how_know_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='cooperation_type',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cooperating_health_assistants',
            field=models.ManyToManyField(blank=True, help_text='Selected health assistants to cooperate with. Empty means all.', related_name='cooperating_doctors', to='api.healthassistant'),
        ),
        migrations.DeleteModel(
            name='DoctorCooperationType',
        ),
    ]
