# Generated by Django 5.2.12 on 2026-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_networkrequest_requeststatuslog_benefactordonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
