# Generated by Django 5.2.12 on 2026-06-02 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactordonation',
            name='campaign_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='benefactordonation',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('campaign', 'Campaign'), ('patient', 'Patient'), ('general', 'General'), ('request', 'Request')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='benefactordonation',
            name='network_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='api.networkrequest'),
        ),
        migrations.AddField(
            model_name='benefactordonation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to='api.patient'),
        ),
        migrations.AddField(
            model_name='benefactordonation',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('gateway_direct', 'Gateway Direct')], default='wallet', max_length=20),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('benefactor', 'Benefactor'), ('patient_escrow', 'Patient Escrow'), ('platform', 'Platform')], max_length=20)),
                ('cached_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_wallet', to='api.patient')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('status', models.CharField(choices=[('created', 'Created'), ('redirected', 'Redirected'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('authority', models.CharField(blank=True, default='', max_length=64, null=True, unique=True)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64, null=True, unique=True)),
                ('gateway', models.CharField(default='zarinpal', max_length=32)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_payments', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_payments', to='api.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('donation_out', 'Donation Out'), ('donation_in', 'Donation In'), ('disbursement', 'Disbursement'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('gateway_payment', 'Gateway Payment'), ('donation', 'Donation'), ('network_request', 'Network Request'), ('disbursement', 'Disbursement')], default='', max_length=30)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to='api.wallet')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('payee_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_approved', to=settings.AUTH_USER_MODEL)),
                ('network_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='api.networkrequest')),
                ('patient_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.wallet')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_record', to='api.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='benefactordonation',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='api.wallettransaction'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('wallet_type', 'benefactor')), fields=('owner_user',), name='unique_benefactor_wallet_per_user'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='api_wallett_wallet__30aaff_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='api_wallett_referen_0ac1ed_idx'),
        ),
    ]
