# Generated by Django 5.2.12 on 2026-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_wallet_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaypayment',
            name='authority',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gatewaypayment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
