# Generated by Django 6.0.6 on 2026-07-03 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_gateway_payment_nullable_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkrequest',
            name='collected_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DonationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='held', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_holds', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds_closed', to=settings.AUTH_USER_MODEL)),
                ('debit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_debits', to='api.wallettransaction')),
                ('network_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_holds', to='api.networkrequest')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_refunds', to='api.wallettransaction')),
                ('release_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_releases', to='api.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['network_request', 'status'], name='api_donatio_network_233465_idx'), models.Index(fields=['benefactor', 'status'], name='api_donatio_benefac_5c3e73_idx')],
            },
        ),
    ]
