# Generated by Django 5.2.12 on 2026-07-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_migrate_admin_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkrequest',
            name='fund_recipient',
            field=models.ForeignKey(blank=True, help_text='HA or doctor who receives the collected funds (financial requests only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_recipient_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='ha_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='consultationType',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('تلفنی', 'تلفنی')], max_length=50),
        ),
        migrations.AlterField(
            model_name='networkrequest',
            name='consultation_mode',
            field=models.CharField(blank=True, choices=[('حضوری', 'حضوری'), ('تلفنی', 'تلفنی')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('benefactor', 'Benefactor'), ('patient_escrow', 'Patient Escrow'), ('platform', 'Platform'), ('staff_payout', 'Staff Payout')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('wallet_type', 'staff_payout')), fields=('owner_user',), name='unique_staff_payout_wallet_per_user'),
        ),
    ]
